### ISSUE TITLE
Errors with webOS4.9 and PicCap 0.2.0 / libvtcapture 

### ISSUE THREAD

**Issue by seacred** [webosbrew/hyperion-webos#29] opened 2022-01-05 00:00 UTC
Hi there, 
i tried to get hyperion-webos via PicCap 0.2.0 working for the last few days.
PicCap 0.1.0 wasn't working either.

I've added my log that was generated after using the following commands:
```
luna-send -n 1 -f 'luna://com.webos.pmlogd/setdevlogstatus' '{"recordDevLogs":true}'
luna-send -n 1 -f luna://com.webos.service.config/setConfigs '{"configs": {"system.collectDevLogs": true}}'
PmLogCtl set 'hyperion-webos_service' debug
tail -F /var/log/messages | grep hyperion
```

after that i hit the "Start" button on Piccap"
[log.txt](https://github.com/webosbrew/hyperion-webos/files/7811091/log.txt)

Settings was set to "all TVs" for generating this log but the other options were also testet - no success.
i hope somebody who got way more in-depth-competence then me is able to provide a tip/solution.

Specs:
- WebOS ver. 4.9
- LG 75UM7000PLA
- Downgrade done
- rooting done

I've already described these circumstances in the OpenLGTV Discord and they told me the problem would be libvtcapture/HAL_VT_Init error(ffffffff). I hope this helps with further investigation.

**Comment by Informatic** [comment] 2022-01-06 14:04
Correction: in this case libvtcapture is missing and libdile_vt errors out during creation. Needs investigation. Duplicate of #23

**Comment by Informatic** [comment] 2022-01-09 13:20
OK, closing this in favour of #23, we'll do further reporting there.

**Closed** 2022-01-09 13:22 UTC
